const dotenv = require("dotenv")
dotenv.config()

module.exports = {
  siteMetadata: {
    title: `Rz Codes`,
    description: `Portfolio of Rabra Hierpa (Rz Codes): full-stack developer, GIS specialist, and open-source contributor. Web apps, mapping projects, technical writing, and graphic design.`,
    author: `Rabra Hierpa`,

    /**
     * Entity fields for the Person/WebSite JSON-LD.
     *
     * These are deliberately SEPARATE from `title`. `title` drives the browser
     * tab suffix and og:site_name, so overloading it to say "Rabra Hierpa —
     * Rz Codes" would rewrite every page title as a side effect.
     */
    entityName: `Rabra Hierpa — Rz Codes`,
    // The site spells it "Rabra"; GitHub is `rabira-hierpa` and the AAU email
    // is rabira.hierpa@. Listing both lets Google merge them into one person
    // instead of two weak entities. Confirm which is canonical.
    alternateNames: [`Rabira Hierpa`, `Rz Codes`, `rzcodes`],
    jobTitle: `Software Engineer & GIS Developer`,
    // Public on LinkedIn and in the work-experience timeline already.
    homeLocation: `Abu Dhabi, United Arab Emirates`,
    alumniOf: `Addis Ababa University`,
    knowsAbout: [
      `Geographic Information Systems`,
      `Web Development`,
      `React`,
      `Next.js`,
      `Public Transport Accessibility`,
      `OpenStreetMap`,
      `Remote Sensing`,
    ],

    siteUrl: `https://rz-codes.com`,
    // 1200x630 share card, generated by scripts/generate-og-image.mjs.
    // Was /icons/icon-512x512.png - a square PWA icon served while
    // twitter:card claimed summary_large_image, so every share rendered wrong.
    defaultOgImage: `/og-image.png`,
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogImageType: `image/png`,
    locale: `en_US`,
    twitterUsername: `rzcodes`,
    sameAs: [
      `https://www.github.com/rabira-hierpa`,
      `https://www.linkedin.com/in/rabira`,
      `https://twitter.com/rzcodes`,
      `https://www.youtube.com/@rzcodes`,
      `https://www.facebook.com/rzcodes`,
      `https://www.tiktok.com/@rzcodes`,
      `https://dev.to/rabra_hierpa`,
      // Merges the academic identity cluster (ResearchGate/AAU/ORCID rank 2-3
      // for the name) with the developer one. TODO: add the AAU staff-profile
      // URL and ORCID once you have them - both are .edu-grade signals.
      `https://www.researchgate.net/profile/Rabra-Hierpa`,
      `https://www.openstreetmap.org/user/Rabira%20Hierpa`,
    ],
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        excludes: [`/404`, `/404.html`, `/dev-404-page`, `/dev-404-page/`],
      },
    },
    `gatsby-plugin-postcss`,
    `gatsby-plugin-image`,
    `gatsby-transformer-json`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/assets/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data/`,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Rz Codes - Portfolio`,
        short_name: `Rz Codes`,
        start_url: `/`,
        background_color: `#000000`,
        theme_color: `#DA5049`,
        display: `minimal-ui`,
        icon: `src/assets/images/logo.svg`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        url: process.env.WPGRAPHQL_URL,
        verbose: false,
        schema: {
          typePrefix: `Wp`,
          requestConcurrency: 2, // Further reduced to 2
          previewRequestConcurrency: 1,
          perPage: 3, // Further reduced to 3 items per page
          timeout: 90000, // Increased timeout
        },
        develop: {
          hardCacheMediaFiles: false,
          hardCacheData: false,
          nodeUpdateInterval: 300000, // Check for updates every 5 minutes instead of frequently
        },
        debug: {
          preview: false,
          graphql: {
            showQueryVarsOnError: true,
          },
        },
        production: {
          hardCacheMediaFiles: true,
          allow404Images: true,
        },
        excludeFieldNames: [
          `blocksJSON`,
          `saveContent`,
          `blocks`,
          `contentParts`,
        ],
        html: {
          fallbackImageMaxWidth: 800,
          createStaticFiles: true,
          useGatsbyImage: false,
        },
        type: {
          Post: {
            limit: process.env.NODE_ENV === `development` ? 5 : 5000,
          },
          CoreParagraphBlockAttributesV2: {
            exclude: true,
          },
          Comment: {
            limit: 0,
          },
          UserRole: {
            limit: 0,
          },
        },
      },
    },
    {
      resolve: `gatsby-plugin-google-gtag`,
      options: {
        trackingIds: [process.env.GA_TRACKING_ID],
        gtagConfig: {
          anonymize_ip: true,
          cookie_expires: 0,
        },
        pluginConfig: {
          head: false,
          delayOnRouteUpdate: 0,
        },
      },
    },
    `gatsby-plugin-gatsby-cloud`,
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
