// Generated by CodiumAI

describe('Header', () => {

    // Renders the header section with the correct logo and site title.
    it('should render the header section with the correct logo and site title', () => {
      // Mock props
      const props = {
        siteTitle: "Test Site Title"
      };

      // Render the Header component with the mock props
      const wrapper = shallow(<Header {...props} />);

      // Assert that the rendered header section contains the correct logo
      expect(wrapper.find('img').prop('src')).toEqual(RzCodesLogo);

      // Assert that the rendered header section contains the correct site title
      expect(wrapper.find('.mt-3').text()).toEqual(props.siteTitle);
    });


});
